QueryBuilder.Tests/QueryBuilderTest.cs
QueryBuilder/Clauses/ColumnClause.cs
QueryBuilder/Compilers/AbstractCompiler.cs
QueryBuilder/Compilers/Compiler.cs
QueryBuilder/Compilers/SqlServerCompiler.cs
QueryBuilder/Query.Select.cs
QueryBuilder/Query.cs

I've implemented a SelectCoalesce method to allow the use of subqueries in coalesce. This could be enhanced to allow the use of more subqueries within select functions.
I've also added a Name property to the query. This prints out a comment in the SQL generated which allows us to locate SQL being executed during a trace.

Select Coalesce and Query Name for Tracing

---

QueryBuilder.Tests/QueryBuilderTest.cs
QueryBuilder/SqlResult.cs

Empty string was treated as number previously.
How it was:
```cs
var query = new Query("table").Select("col").Where("col", "");
new Compiler().Compile(query).ToString(); 
// will return `SELECT col FROM table WHERE col = ` 
// but should return `SELECT col FROM table WHERE col = ''` 
```

Updated isNumber check in SqlResult.ToString method

---

QueryBuilder.Tests/CompilerTest.cs
QueryBuilder.Tests/QueryBuilder.Tests.csproj
QueryBuilder/Compilers/Compiler.cs
QueryBuilder/Properties/AssemblyInfo.cs
QueryBuilder/QueryBuilder.csproj

Fixes issue #80.
The parameter bindings were not cleared after each compilation. This has caused two issues:
- the pagination was broken, after the second page the data repeats, because only the first two parameters were being injected in place of the placeholders.
- longer sessions with the database server were returning an error after some time saying 
```
The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
```

Fix for sql parameter binding

---

QueryBuilder.Tests/QueryBuilderTest.cs
QueryBuilder/SqlResult.cs

Instead of parsing the binding string value I changed it to check it's type instead. This is (in my opinion) a more reliable check. Also, you run into potential 'Error converting data type varchar to numeric' type issues when debugging, thus having to manually edit the query.

Updated ToString() to check number type

---

QueryBuilder/Compilers/Compiler.cs

This is needed, because Oracle doesn't require AS in column alias syntax, and forbids AS in table alias syntax.
Source: https://www.techonthenet.com/oracle/alias.php
AS in CTE functions is left intentionally.

#oracleSupport - move AS keyword to variable

---

QueryBuilder.Tests/QueryBuilderTest.cs
QueryBuilder.Tests/QueryJoinTest.cs
QueryBuilder/Compilers/Compiler.cs

Currently results in a trailing space character ` ` on the line before the first join line, which is not ideal.
WIP

Leading newline character before every join

---

QueryBuilder/Compilers/Compiler.Conditions.cs
QueryBuilder/Compilers/Compiler.cs

1. Use thread-safe logic for FindCompilerMethodInfo

Optimize MethodsCache

---

QueryBuilder.Tests/OracleLegacyLimit.cs
QueryBuilder.Tests/OracleLimitTests.cs
QueryBuilder/Compilers/OracleCompiler.cs
sqlkata.sln

This new class supports both LIMIT/OFFSET (12c) and legacy (< 12c) ROWNUMBER pagination syntax similar to how it is done for SqlServer. Also added additional tests and moved them (together with the existing Oracle11gCompiler tests) into the SqlKata.Tests namespace.
This is a step closer to full-blown Oracle support IMO #56

Added a generic Oracle class 

---

QueryBuilder/Compilers/PostgresCompiler.cs

Now `_db.Query("...").InsertGetId<int>(obj);` always returns 0 (i.e. `default(int)`), because sql `"SELECT lastval()"` returns lastval in column named "lastval" which doesn't map to `InsertGetIdRow<T>.Id`.
Tested on postgresql 10.

Fix lastval in PostgresCompiler for SqlKata.Execution

---

QueryBuilder.Tests/GeneralTests.cs
QueryBuilder.Tests/HelperTests.cs
QueryBuilder.Tests/SelectTests.cs
QueryBuilder/Compilers/Compiler.cs
QueryBuilder/Helper.cs

Here is a commit to allow for escaping identifiers #215

Adds ability to escape identifiers w/ tests

---

Program/Program.cs
QueryBuilder/Include.cs
QueryBuilder/Query.cs
SqlKata.Execution/QueryFactory.Extensions.cs
SqlKata.Execution/QueryFactory.cs

Provide the **Include** feature,
```cs
var postsWithAuthors = db.Query("Posts").Include("Author", db.Query("Authors")).Get();
```
will returns
```json
[
{
"Id": 1,
"Name": "How to include nested rows in SqlKata",
"AuthorId": 22,
"Author": {
"Id": 22,
"Name": "Ahmad"
}
}
]
```
Isn't awesome ? 😎

Support includes for *dynamic* queries

---

QueryBuilder.Tests/InsertTests.cs
QueryBuilder.Tests/UpdateTests.cs
QueryBuilder/ColumnAttribute.cs
QueryBuilder/IgnoreAttribute.cs
QueryBuilder/Query.Insert.cs
QueryBuilder/Query.Update.cs

Basically I add the attribtues ignore and column  and the functionality to produce the expected output as @ahmad-moussawi requested it in the issue feature_request #212.

adding ignore and column attributes

---

QueryBuilder.Tests/GeneralTests.cs
QueryBuilder/BaseQuery.cs
QueryBuilder/Clauses/FromClause.cs
QueryBuilder/Clauses/LimitClause.cs
QueryBuilder/Clauses/OffsetClause.cs
QueryBuilder/Compilers/SqlServerCompiler.cs
QueryBuilder/Query.cs

Fixes #239 
Turns out I was right the first time, even though my fork was out of date. If the `Engine` isn't preserved during `FromClause.Clone()`, then 2 of the 3 unit tests I added fail.

Include the Engine when cloning a FromClause

---

QueryBuilder.Tests/UpdateTests.cs
QueryBuilder/ColumnAttribute.cs
QueryBuilder/Query.Insert.cs
QueryBuilder/Query.Update.cs

@ahmad-moussawi  ready for request https://github.com/sqlkata/querybuilder/issues/246

Primary key attr

---

QueryBuilder.Tests/SelectTests.cs
QueryBuilder/Compilers/Compiler.cs

This PR fixes bad compilation of `having` clause when there is more than one having component. Example:
```
Query:
new Query("Table1").Having("Column1", ">", 1).Having("Column2", "=", 1);
Compiled query:
SELECT * FROM [Table1] HAVING [Column1] > 1, AND HAVING [Column2] = 1
```
With tix fix it would compile to:
`SELECT * FROM [Table1] HAVING [Column1] > 1 AND [Column2] = 1`

Fix `having` clause compilation

---

QueryBuilder.Tests/DefineTest.cs
QueryBuilder.Tests/SqlServer/NestedSelectTests.cs
QueryBuilder/Base.Where.cs

parameterized  top (@p0) in subquery leeds to performance issue

Avoid parameter sniffing for exists subquery

---

QueryBuilder.Tests/SelectTests.cs
QueryBuilder/Base.Where.cs
QueryBuilder/Clauses/ConditionClause.cs
QueryBuilder/Compilers/Compiler.Conditions.cs
QueryBuilder/Query.Having.cs

As discussed in the issue I created the implementation I had in mind, added a number of tests and it seems to work fine, other tests didn't fail as a result of the addition.

Adding Escape clause to LIKE operator conditions - related to #237

---

SqlKata.Execution/Query.Extensions.Async.cs

Added a new extension for InsertGetIdAsync which takes a ReadOnlyDictionary.  Resolves the issue with "Parameter count mismatch"

Resolution for sqlkata/querybuilder#33

---

QueryBuilder/Compilers/ConditionsCompilerProvider.cs

Avoids a possible NullReferenceException when checking for the existence of a key in a non-thread-safe dictionary.
Although the dictionary is only written to inside the `lock`, accessing it outside the lock while any number of other threads are potentially writing to it can cause a NullPointerException (eg: if the internal buckets are being resized, or are half-way through being written to).
Reads need to happen inside the lock, which can be solved by simply removing the 3 lines as shown here. (You could also achieve the same thing by using a ConcurrentDictionary instead and the GetOrAdd method to specify how to populate the entry when it's missing)
You can trigger this bug fairly easily by setting up a few threads which all call `ConditionsCompilerProvider::GetMethodInfo` in parallel …

Race condition fix for ConditionsCompilerProvider dictionary access

---

Program/Program.cs
SqlKata.Execution/Query.Extensions.cs
SqlKata.Execution/QueryFactory.cs

Adds support for the following execution methods:
- Exists()
- NotExists()
```cs
var exists = db.Query("Users").WhereFalse("Active").Exists();
```

add Exists and NotExists

---

README.md

Documentation uses `QueryFactory` class without saying that it is not present in the main package, and that it needs the SqlKata.Execution package.
Also, there is no hint about the use of Dapper in the SqlKata.Execution package.

Clarified packages use and dependency on Dapper

---

QueryBuilder.Tests/GeneralTests.cs
QueryBuilder.Tests/InfrastructureTests.cs
QueryBuilder.Tests/InsertTests.cs
QueryBuilder.Tests/UpdateTests.cs
QueryBuilder/Base.Where.cs
QueryBuilder/BaseQuery.cs
QueryBuilder/Clauses/ConditionClause.cs
QueryBuilder/ColumnAttribute.cs
QueryBuilder/Compilers/ConditionsCompilerProvider.cs
QueryBuilder/Compilers/SqliteCompiler.cs
QueryBuilder/Query.Having.cs
QueryBuilder/Query.Insert.cs
QueryBuilder/Query.Update.cs
QueryBuilder/Query.cs
QueryBuilder/SqlResult.cs
SqlKata.Execution/Query.Extensions.cs
SqlKata.Execution/QueryFactory.cs

Now the `values` parameter of `.Insert`, `.Update`, `.Where` & `.Having` accepts any implementation of `IEnumerable<KeyValuePair<string, object>>`, including [`IDictionary<string, object>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2) & [`ExpandoObject`](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.expandoobject).

Added support for any IEnumerable<KeyValuePair<string, object>> as values parameter

---

QueryBuilder/Base.Where.cs
QueryBuilder/Compilers/OracleCompiler.cs

WhereDatePart must .ToLowerInvariant() the "part" var for later switchs dont miss and produce the default behavior.

WhereDatePart uses ToLowerInvariant()

---

QueryBuilder.Tests/InsertTests.cs
QueryBuilder.Tests/ParameterTypeTests.cs
QueryBuilder.Tests/UpdateTests.cs

This makes sure that all tests always use the UTC time zone when constructing a `DateTime`. This doesn't change the existing tests, but it allows us to reject all 'unpredictable' times in our custom (downstream) Snowflake compiler.
This is an example of a change which is needed only for our custom compiler, but which we wouldn't want to keep in a local change on our repository for maintainability reasons. I.e. keeping this as a commit local to our downstream branch would be a constant source of potential merge conflicts, so we would like to upstream this. We'd like to use this as opportunity to discuss how to best handle such changes.

Make sure that tests use a predictable time zone.

---

QueryBuilder/Helper.cs

With the previous implementation, large queries took a very long time to compile.

changing string concatenation with StringBuilder.Append in Helper.ReplaceAll

---

QueryBuilder/QueryBuilder.csproj

… from PackageLicenseUrl to PackageLicenseExpression to conform with current standard.
See https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#license-url-deprecation
and https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file.
This makes the license type machine readable and thus shows up nicely on NuGet.org or other tools, like WhiteSource.

Change License Tag in the *.csproj file

---

QueryBuilder/Compilers/SqlServerCompiler.cs

This addresses #545 and is meant to match the expected behaviour of the docs.

Disable SQL Legacy Pagination by default

---

SqlKata.Execution/QueryFactory.cs

When you use .Include on a nullable FK, an exception is thrown during the dynamicResult cast. Adding a guard here now allows mapping to continue as expected.

Include/IncludeMany on nullable FK no longer throws exception.

---

QueryBuilder.Tests/SelectTests.cs
QueryBuilder/Compilers/Compiler.cs
QueryBuilder/Query.Join.cs

This PR is addressing some of the issues reported earlier #123 #104 
where people want to select some static values or native database functions or to support column reusability of cross/outer apply. The majority of the database provider supports this.
Let me know your thoughts on this one.

allow select without table to support cross apply

---

QueryBuilder.Tests/SelectTests.cs
QueryBuilder/Compilers/Compiler.cs

this is in continuation of supporting cross apply addressed in #541 
With this PR one can put where clause when there is no table to select
` SELECT 1 WHERE 1=1`

compile where clause when no table is present

---

QueryBuilder/Base.Where.cs
QueryBuilder/Query.Having.cs

No need for comments to assume male developer gender

De-gender comments

---

QueryBuilder/QueryBuilder.csproj
SqlKata.Execution/SqlKata.Execution.csproj

Current nuget package does not include the documentation file since it is never generated. 
This prevents consumers from seeing any of the XML documentation provided within the source code.
This PR simply turns that functionality on by placing the files in their respective compile folders

Include XML Documentation File

---

QueryBuilder.Tests/MySqlExecutionTest.cs

Add more execution tests for:
- Inline Table
- Variable definition
Table Creation/Drop helpers

Add more execution test for InlineTable, Variable

---

QueryBuilder.Tests/MySqlExecutionTest.cs
QueryBuilder.Tests/QueryBuilder.Tests.csproj
QueryBuilder.Tests/QueryFactoryExtension.cs
QueryBuilder.Tests/SQLiteExecutionTest.cs

Add basic execution tests for SQLite

Feature 605 sqlite execution test

---

SqlKata.Execution/SqlKata.Execution.csproj

reason: TimeSpan will be parsed as default to :time for Postgres under this version, newer version fixes the issue and sets the default to :interval. (fixed npgsql issue)

update dapper version from 1.50.5 to 2.0.123

---

QueryBuilder.Tests/DeleteTests.cs
QueryBuilder/Compilers/Compiler.cs

This MR add the support for "delete with join" statements
The initial work was originally contributed by @mathijs-dumon

Issue 182 - delete join support

---

QueryBuilder/Compilers/Compiler.cs
QueryBuilder/Compilers/FirebirdCompiler.cs
QueryBuilder/Compilers/MySqlCompiler.cs
QueryBuilder/Compilers/OracleCompiler.cs
QueryBuilder/Compilers/SqlServerCompiler.cs
QueryBuilder/Compilers/SqliteCompiler.cs

Accidentally closed the old PR #592

Fix places where the parameterPlaceholder is hardcoded to a ? 

---

QueryBuilder.Tests/MySqlExecutionTest.cs
QueryBuilder.Tests/SQLiteExecutionTest.cs
QueryBuilder.Tests/SelectTests.cs
QueryBuilder/Clauses/ColumnClause.cs
QueryBuilder/Compilers/Compiler.cs
QueryBuilder/Compilers/PostgresCompiler.cs
QueryBuilder/Compilers/SqliteCompiler.cs
QueryBuilder/Query.Select.cs

This PR adds the support for the `SelectAggregate` method and it's siblings `SelectSum`, `SelectMax`, `SelectMin`, `SelectAvg`, `SelectCount` methods, this is better than using `SelectRaw`.
All these methods accepts an optional `filter` parameter to filter the aggregated column based on a specified conditions, this will translate to the **Aggregation Filter** clause on supported compilers like PostgreSQL, and SQLite with a fallback to `CASE WHEN` statement for the unsupported ones.
Related #507

Iss 507 support filter clause

---

QueryBuilder.Tests/SelectTests.cs
QueryBuilder/Base.Where.cs
QueryBuilder/Compilers/Compiler.Conditions.cs
QueryBuilder/Compilers/Compiler.cs

This PR add a new property `OmitSelectInsideExists` to avoid removing the select columns from `WhereExists`
The new property defaults to true to be compatible with previous versions.
related #581

Iss 581 where exists remove select

---

QueryBuilder.Tests/Oracle/OracleInsertManyTests.cs
QueryBuilder/Compilers/Compiler.cs
QueryBuilder/Compilers/OracleCompiler.cs

This is a replacement PR for this older branch: [issue-192](https://github.com/sqlkata/querybuilder/tree/issue-192)
I compared the test case that was in the old branch, my tests are equivalent.
The generated SQL is slightly different, (INSERT ALL vs UNION ALL) but functionally equivalent. The INSERT ALL approach is more in line with what other dialects do.
This fixes #192

Fix for Oracle insert many

---

QueryBuilder.Tests/SelectTests.cs
QueryBuilder/Helper.cs

Hi, 
This PR's purpose is to allow expanded select to accept multiline inputs. (currently any multiline expanded select compiles a wrong SQL query)
Expanded select is a great feature for small queries, but for big ones it quickly became complicated to read the query.
For example, the following Query : 
```csharp
var q = new Query().From("users").Select("users.{id,name, age, password, description, admin, last_update, company, title, addr1 as AddressNumber, addr2 as AddressStreet, addr3 as AddressPostalCode, addr4 as AddressCountry, dept, /* other fields */ }");
```
is much more readable this way : 
```csharp
var q = new Query().From("users").Select(@"users.{
id, name, age, password, description, //allow multiple parameters on the same line
admin, last_update, //allow multiple lines …
```

allow expanded select to be multiline

---

QueryBuilder.Tests/Firebird/FirebirdLimitTests.cs
QueryBuilder.Tests/HelperTests.cs
QueryBuilder.Tests/MySql/MySqlLimitTests.cs
QueryBuilder.Tests/Oracle/OracleLegacyLimitTests.cs
QueryBuilder.Tests/Oracle/OracleLimitTests.cs
QueryBuilder.Tests/PostgreSql/PostgreSqlLimitTests.cs
QueryBuilder.Tests/SqlServer/SqlServerLegacyLimitTests.cs
QueryBuilder.Tests/SqlServer/SqlServerLimitTests.cs
QueryBuilder.Tests/SqlServer/SqlServerTests.cs
QueryBuilder.Tests/Sqlite/SqliteLimitTests.cs
QueryBuilder/Compilers/Compiler.cs
QueryBuilder/Compilers/FirebirdCompiler.cs
QueryBuilder/Compilers/MySqlCompiler.cs
QueryBuilder/Compilers/OracleCompiler.cs
QueryBuilder/Compilers/SqlServerCompiler.cs
QueryBuilder/Compilers/SqliteCompiler.cs
QueryBuilder/Helper.cs
QueryBuilder/SqlResult.cs

Provides the feasibility to have parameter placeholder in the select statement by escaping them. This also provides the capability to override the parameter placeholder and escape character.
Ex => var query = new Query("table").Select("Column\\?");
produces => SELECT [Column?] FROM [table]
[https://github.com/sqlkata/querybuilder/issues/461](url)

Escape parameter place holder
