QueryBuilder.Tests/Program.cs, QueryBuilder.Tests/QueryBuilder.Tests.csproj, QueryBuilder/QueryBuilder.csproj, sqlkata.sln
Wanted to do the small amount of work to support net45 so that existing projects don't have to reference and include libraries for all of which that is netstandard. Tests passing.
=> Support net45

QueryBuilder/Compilers/SqlServerCompiler.cs
issue:  #13 
- change the component name for column clause check from 'columns' to 'select'
- add an alias name to the subquery
=> Fix SqlServer bug in pagination

QueryBuilder/Base.Where.cs, QueryBuilder/Query.Insert.cs, QueryBuilder/Query.Update.cs
This way I don't have to convert my `ImmutableDictionary` before calling Insert. =)
=> change Insert signature to take IReadOnlyDictionary instead of Dictionary

QueryBuilder.Tests/QueryBuilderTest.cs, QueryBuilder/Compilers/Compiler.cs, QueryBuilder/Query.Insert.cs
Add a method to accept multi values and change compiler class to handle it.
Fix #36
If there is any problem or suggestion please let me now.
Thanks
=> Add support multi insert records

.editorconfig, QueryBuilder/BaseQuery.cs, QueryBuilder/Query.Insert.cs, QueryBuilder/Query.Update.cs
* Updated BackupNullValues & RestoreNullValues
* Added editor config
=> Code refactoring (BackupNullValues & RestoreNullValues)

QueryBuilder.Tests/HelperTest.cs, QueryBuilder/Base.Where.cs, QueryBuilder/BaseQuery.cs, QueryBuilder/Clauses/AggregateClause.cs, QueryBuilder/Clauses/ColumnClause.cs, QueryBuilder/Clauses/ConditionClause.cs, QueryBuilder/Clauses/LimitClause.cs, QueryBuilder/Compilers/Compiler.cs, QueryBuilder/Compilers/SqlServerCompiler.cs, SqlKata.Execution/PaginationResult.cs, SqlKata.Execution/Query.AggregateExtensions.Async.cs, SqlKata.Execution/Query.AggregateExtensions.cs, SqlKata.Execution/Query.Extensions.Async.cs, SqlKata.Execution/Query.Extensions.cs, SqlKata.Execution/QueryFactory.cs
Hi, I'm starting about support DDL query.
Before, i found several tiny improve points in files. (not critical.. really smalls..:joy:) and this PR just fix them.
I think we need to create PR or Issue template, Contribute guide.
If we are with stylecop.settings or [Rider, Resharper editorconfig code-style custom properties](https://www.jetbrains.com/help/rider/EditorConfig_Index.html), more made better about writing codes.
Could you review above the points?
---
**chages**
- Fix wrong comments about method parameters
- Remove unused import
=> Fix wrong comments, Optimization unused import statments

QueryBuilder.Tests/HelperTest.cs, QueryBuilder/Helper.cs, QueryBuilder/Query.Combine.cs, QueryBuilder/Query.Having.cs, QueryBuilder/Query.Select.cs, QueryBuilder/Query.cs
Hi
i thought i could improve the helper class by looking  at the code for about building queries.
All changes for lazy processing with linq
- `AllIndexesOf`, use `yield` statements
- `ReplaceAll`, use LINQ `Aggregate` method
- `Flatten`, use LINQ `SelectMany`
and do you have any test naming rule? maybe if you don't like this style, just comment me 😄
=> Improve Helper class with adding tests

QueryBuilder.Tests/NestedSelectTests.cs
=> Add failed test for show bug in nested limit query

QueryBuilder/Compilers/Compiler.Conditions.cs
value is lowercase if parameter CaseSensitive is false
=> Fix CompileBasicStringCondition

QueryBuilder/Compilers/SqliteCompiler.cs
=> Select statement is required to return the last rowid

QueryBuilder/Compilers/Compiler.cs
Build component cte moved to virtual function
=> Compiler Compile Cte

QueryBuilder.Tests/Oracle/OracleDateConditionTests.cs, QueryBuilder/Compilers/OracleCompiler.cs, sqlkata.sln
=> Adding oracle compiler date where & where part clause support - fixes #256

QueryBuilder.Tests/WithVarTest.cs, QueryBuilder/Base.Where.cs, QueryBuilder/Clauses/WithVarClause.cs, QueryBuilder/Compilers/Compiler.Conditions.cs, QueryBuilder/Compilers/Compiler.cs, QueryBuilder/Compilers/FirebirdCompiler.cs, QueryBuilder/Query.cs, QueryBuilder/SqlResult.cs
@ahmad-moussawi ready! The feature-request is #184
=> With var clause2

QueryBuilder/Compilers/SqliteCompiler.cs
Fix Sqlite InsertGetId always empty
=> Sqlite last insert id

QueryBuilder/QueryBuilder.csproj
I've just rename the assembly "SqlKata"
=> Issue-109 Rename generated DLL to SqlKata.dll instead of QueryBuilder.dll

Program/Program.cs, QueryBuilder/Expressions.cs, QueryBuilder/UnsafeLiteral.cs
=> make quote replacement optional in UnsafeLiteral

QueryBuilder/SqlResult.cs
Hi, it's request for fix double parce in issue  #406
=> fix: issue #406

QueryBuilder/Compilers/Compiler.cs
Solves https://github.com/sqlkata/querybuilder/issues/449
=> Mark Compile methods as protected virtual

SqlKata.Execution/QueryFactory.cs
transaction parameter added to invocations of PaginateAsync<T> and PaginationResult<T>.Next methods within Chunk and ChunkAsync methods.
=> transaction parameter within Chunk and ChunkAsync methods

QueryBuilder.Tests/WhereTests.cs, QueryBuilder/Compilers/Compiler.Conditions.cs
=> Grouped filters

QueryBuilder.Tests/SelectTests.cs, QueryBuilder/Query.Select.cs
=> Add Select overload with IEnumerable<string>

QueryBuilder.Tests/GeneralTests.cs, QueryBuilder/Clauses/FromClause.cs, QueryBuilder/Compilers/Compiler.cs, QueryBuilder/Compilers/FirebirdCompiler.cs, QueryBuilder/Compilers/OracleCompiler.cs, QueryBuilder/Compilers/SqlServerCompiler.cs, QueryBuilder/Query.cs
Pull request conflicts resolved https://github.com/sqlkata/querybuilder/pull/304
=> Allow for ad-hoc table CTEs with parameterized data

QueryBuilder.Tests/ExecutionTests.cs, SqlKata.Execution/Properties/AssemblyInfo.cs, SqlKata.Execution/Query.Extensions.cs
=> fix Query Timeout is overridden

QueryBuilder.Tests/Firebird/FirebirdLimitTests.cs, QueryBuilder.Tests/MySql/MySqlLimitTests.cs, QueryBuilder.Tests/Oracle/OracleLegacyLimitTests.cs, QueryBuilder.Tests/Oracle/OracleLimitTests.cs, QueryBuilder.Tests/PostgreSql/PostgreSqlLimitTests.cs, QueryBuilder.Tests/SqlServer/SqlServerLimitTests.cs, QueryBuilder.Tests/Sqlite/SqliteLimitTests.cs, QueryBuilder/Clauses/OffsetClause.cs, QueryBuilder/Query.cs
=> iss-532: Offset is now long instead of int

QueryBuilder/QueryBuilder.csproj, SqlKata.Execution/SqlKata.Execution.csproj
=> Fix license URL

QueryBuilder.Tests/Oracle/OracleDateConditionTests.cs, QueryBuilder.Tests/Oracle/OracleLimitTests.cs
I am verifying that the project is alive
=> Added `readonly` modifier to `private` fields that are never modified
